image: mcr.microsoft.com/dotnet/core/sdk:3.1
pipelines:
  default:
      - step:
          name: Build app
          caches:
            - dotnetcore
          script:
          - dotnet restore $SOLUTION_NAME.sln
          - dotnet build --no-restore $SOLUTION_NAME.sln --configuration $CONFIGURATION
